/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gedeon1;

import base_dato.ManejadorSQL;
import base_dato.validaciones;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
 
public class inicio extends javax.swing.JFrame {
 ManejadorSQL m;
 validaciones v = new validaciones();
    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        
   
        mensaje.setVisible(false);
        validaciones v = new validaciones();
        m = new ManejadorSQL("postgres", "localhost", "freddy", "1234", "org.postgresql.Driver", "5432", "jdbc:postgresql", "2", v);
        usuario.setEditable(true);
        usuario.setVisible(true);
         this.setLocationRelativeTo(null);//esta linea posiciona la ventana en el centro de la pantalla
         Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();//para que la ventana aparezca maximizada
         this.setSize(screenSize);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        titulo = new javax.swing.JLabel();
        nombre_usuario = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        nombre_clave = new javax.swing.JLabel();
        clave = new javax.swing.JPasswordField();
        mensaje = new javax.swing.JLabel();
        boton_acaeptar = new org.edisoncor.gui.button.ButtonAqua();
        buttonAqua1 = new org.edisoncor.gui.button.ButtonAqua();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj.jpg"))); // NOI18N

        titulo.setFont(new java.awt.Font("Serif", 2, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Juego Biblico Interactivo");

        nombre_usuario.setBackground(new java.awt.Color(255, 51, 51));
        nombre_usuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombre_usuario.setForeground(new java.awt.Color(255, 255, 255));
        nombre_usuario.setText("Usuario:");

        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usuarioKeyTyped(evt);
            }
        });

        nombre_clave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombre_clave.setForeground(new java.awt.Color(255, 255, 255));
        nombre_clave.setText("Contraseña:");

        clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveActionPerformed(evt);
            }
        });

        mensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mensaje.setText("jLabel1");

        boton_acaeptar.setText("Aceptar");
        boton_acaeptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_acaeptarMouseClicked(evt);
            }
        });

        buttonAqua1.setText("salir");
        buttonAqua1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAqua1MouseClicked(evt);
            }
        });
        buttonAqua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(nombre_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelImage1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelImage1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelImage1Layout.createSequentialGroup()
                                        .addComponent(buttonAqua1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(boton_acaeptar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 98, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addContainerGap(389, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(371, 371, 371))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton_acaeptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAqua1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(mensaje)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioKeyTyped

    private void boton_acaeptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_acaeptarMouseClicked
String estatus, usr, clv;
        
        usr = usuario.getText();
        clv = clave.getText();

        if (usr.equals("") || clv.equals("")) {
            mensaje.setVisible(true);
            mensaje.setText("Todos los campos deben estar llenos");
            mensaje.setForeground(Color.RED);
        } else {
            
            boolean existe = m.Select3("usuarios", "*", "tx_login='" + usr + "' and clave='" + clv + "'");
            if (existe == true) {
                
                try {
                    int id_rol = m.Select2("usuarios", "*", "tx_login='" + usr + "' and clave='" + clv + "'").getInt("id_rol_usr");
                    estatus=m.Select2("usuarios", "*", "tx_login='" + usr + "' and clave='" + clv + "'").getString("id_estatus");
                    String nb_estatus=m.Select2("tbl_estatus", "*", "id_estatus='" + estatus + "'").getString("nb_estatus");
                    if(nb_estatus.equals("inactivo")){
                        JOptionPane.showMessageDialog(null , "Su cuenta en el sistema a si desacctivada, comuniquese con su profesor");
                        usuario.setText("");
                        clave.setText("");
                        mensaje.setVisible(false);
                        
                    }else{
                    
                        String id_usuario = m.Select2("usuarios", "*", "tx_login='" + usr + "' and clave='" + clv + "'").getString("id_usuario");
                        
                        m.id_usuario=id_usuario;
                        int id_admin, id_estu, id_maestro;
                        id_admin = m.Select2("tbl_rol_usr", "*", "nb_rol_usr='Administrador'").getInt("id_rol_usr");
                        id_estu = m.Select2("tbl_rol_usr", "*", "nb_rol_usr='Estudiante'").getInt("id_rol_usr");
                        id_maestro = m.Select2("tbl_rol_usr", "*", "nb_rol_usr='Maestro'").getInt("id_rol_usr");
                        String id_est_admin, id_est_estu, id_est_maestro, nb_est_admin, nb_est_estu,nb_est_maestro;
                            id_est_admin = m.Select2("tbl_rol_usr", "*", "nb_rol_usr='Administrador'").getString("id_estatus");
                        id_est_estu = m.Select2("tbl_rol_usr", "*", "nb_rol_usr='Estudiante'").getString("id_estatus");
                        id_est_maestro = m.Select2("tbl_rol_usr", "*", "nb_rol_usr='Maestro'").getString("id_estatus");
                        nb_est_admin=m.Select2("tbl_estatus", "*", "id_estatus='" + id_est_admin + "'").getString("nb_estatus");
                        nb_est_estu=m.Select2("tbl_estatus", "*", "id_estatus='" + id_est_estu + "'").getString("nb_estatus");
                        nb_est_maestro=m.Select2("tbl_estatus", "*", "id_estatus='" + id_est_maestro + "'").getString("nb_estatus");
                          
                        if(nb_est_admin.equals("inactivo")&&id_rol==id_admin){
                        JOptionPane.showMessageDialog(null , "Se ha negado el accseso a los usuarios de tipo administrador");   
                        }else if(nb_est_maestro.equals("inactivo")&&id_rol==id_maestro){
                            JOptionPane.showMessageDialog(null , "Se ha negado el accseso a los usuarios de tipo profesor");   
                        }else if(nb_est_estu.equals("inactivo")&&id_rol==id_estu){
                            JOptionPane.showMessageDialog(null , "Se ha negado el accseso a los usuarios de tipo estudiante");   
                        }
//aqui......
                        if (id_rol == id_admin || id_rol == id_maestro) {
                           
                        if(clv.equals("12345")){
                             JOptionPane.showMessageDialog(null , "usted ha sido inscrito recientemente... a continuacion culminara su fase de registro");
                             admin_usuario ad = new admin_usuario (m);
                             ad.setVisible(true);
                             m.setClave(clv);
                              m.setNombre_usuario(usr);
                                this.dispose();
                              
                        }else{
                            m.id_rol=id_rol;
                            m.setNombre_usuario(usr);
                            m.setClave(clv);
                            String nombre_rol=m.Select2("tbl_rol_usr", "*", "id_rol_usr="+id_rol+"").getString("nb_rol_usr");
                            m.setTipo(nombre_rol);
                            menu_principal mp = new menu_principal(m);
                            mp.setVisible(true);
                            this.dispose();
                            
                        } 
                        }
                            
                        else if("12345".equals(clv)) {
                                JOptionPane.showMessageDialog(null , "usted ha sido inscrito recientemente... a continuacion culminara su fase de registro");
                                String nombre_rol=m.Select2("tbl_rol_usr", "*", "id_rol_usr="+id_rol+"").getString("nb_rol_usr");
                                m.id_rol=id_rol;
                                m.setTipo(nombre_rol);
                                  m.setNombre_usuario(usr);
                            m.setClave(clv);
                                admin_usuario ad = new admin_usuario (m);
                                ad.setVisible(true);
                                this.dispose();
                                
                            } else{
                            menu_juego mj = new menu_juego();
                              m.setNombre_usuario(usr);
                            m.setClave(clv);
                            mj.setVisible(true);
                            this.dispose();
                            
                        
                        
                        
                        
                        }  
                        }
                        
                    } catch (SQLException ex) {                
                    Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
         
                }else {
                mensaje.setVisible(true);
                mensaje.setText("Usuario o Clave incorrecta");
                mensaje.setForeground(Color.RED);
                }
            }         // TODO add your handling code here:
    }//GEN-LAST:event_boton_acaeptarMouseClicked

    private void buttonAqua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAqua1ActionPerformed

    private void buttonAqua1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAqua1MouseClicked
        // TODO add JOptionPane.showMessageDialog(null, "Gracias por Jugar...Vuelve Pronto");
        JOptionPane.showMessageDialog(null, "Gracias por Jugar...Vuelve Pronto");
        System.exit(0);         
    
    }//GEN-LAST:event_buttonAqua1MouseClicked

    private void claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveActionPerformed

    
     public void main(ManejadorSQL m2) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
m=m2;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_principal(m).setVisible(true);
                
               
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAqua boton_acaeptar;
    private org.edisoncor.gui.button.ButtonAqua buttonAqua1;
    private javax.swing.JPasswordField clave;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel nombre_clave;
    private javax.swing.JLabel nombre_usuario;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
