/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package millonario;

import ahorcado.etapa1;
import base_dato.ManejadorSQL;
import base_dato.validaciones;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import gedeon1.Gedeon1;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.Timer;
/**
 *
 * @author ejercito
 */
public class gedeonario_preguntas extends javax.swing.JFrame {
  String opcion;
   int cp=2,comdin=0;
   boolean comdin2 = true;
    validaciones v = new validaciones();
    ManejadorSQL db = new ManejadorSQL("postgres", Gedeon1.ipcondb, "freddy", "1234", "org.postgresql.Driver", "5432", "jdbc:postgresql", "2", v);
    /**
     * Creates new form gedeonario_preguntas
     */
    public gedeonario_preguntas() {
        initComponents();
        ImageIcon img = new ImageIcon(getClass().getResource(Gedeon1.icono));
        this.setIconImage(img.getImage());
   
        this.setLocationRelativeTo(null);
       //jLabel2.setFocusable(true);
        actualizarListas();
        cargar_primera_pregunta();
        jtfopciona.setForeground(Color.darkGray);
        jtfopcionb.setForeground(Color.darkGray);
        jtfopcionc.setForeground(Color.darkGray);
        jtfopciond.setForeground(Color.darkGray);
        jtfopciona.setEditable(false);
        jtfopcionb.setEditable(false);
        jtfopcionc.setEditable(false);
        jtfopciond.setEditable(false);
        this.llenar_label_niveles();
        niveles.get(nivel).setForeground(Color.WHITE);
       
    }
 public void actualizarListas() {
        try{
            
            
            //Statement stmt = Gedeon1.db.getConexion().createStatement();
            ResultSet rs = db.Select("tbl_preguntas", "tx_preguntas");//stmt.executeQuery("SELECT tx_palabra, int_puntos FROM tbl_palabra WHERE int_dificultad = "+dificultad);
            
        
        //rs = Gedeon1.db.Select2("tbl_palabra", "tx_palabra, int_puntos", "int_dificultad = "+dificultad);
        
       // palabras.clear();
       // puntos.clear();
        
            while(rs.next()) {
               palabras.add(rs.getString("tx_preguntas"));
                            }
        
         } catch (SQLException ex) {
                Logger.getLogger(etapa1.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    //Array preguntas cargadas
    ArrayList<String> preguntas_a_mostrar = new ArrayList<String>();   
       
    //Artray de Preguntas
    ArrayList<String> palabras = new ArrayList<String>();
    ArrayList<javax.swing.JLabel> niveles = new ArrayList<javax.swing.JLabel>();
    int nivel = 0;
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        jtfopcionb = new javax.swing.JTextField();
        jlbopcionc = new javax.swing.JLabel();
        jlbopcionb = new javax.swing.JLabel();
        jlbopciond = new javax.swing.JLabel();
        jlbopciona = new javax.swing.JLabel();
        jtfopciond = new javax.swing.JTextField();
        jtfopcionc = new javax.swing.JTextField();
        jtfopciona = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();
        panelShadow1 = new org.edisoncor.gui.panel.PanelShadow();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        panelImage6 = new org.edisoncor.gui.panel.PanelImage();
        panelImage7 = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen1.jpg"))); // NOI18N

        jtfopcionb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfopcionb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfopcionbActionPerformed(evt);
            }
        });

        jlbopcionc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbopcionc.setForeground(new java.awt.Color(0, 0, 204));
        jlbopcionc.setText("C");
        jlbopcionc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbopcionc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbopcioncMouseClicked(evt);
            }
        });

        jlbopcionb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbopcionb.setForeground(new java.awt.Color(0, 0, 204));
        jlbopcionb.setText("B");
        jlbopcionb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbopcionb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbopcionbMouseClicked(evt);
            }
        });

        jlbopciond.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbopciond.setForeground(new java.awt.Color(0, 0, 204));
        jlbopciond.setText("D");
        jlbopciond.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbopciond.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbopciondMouseClicked(evt);
            }
        });

        jlbopciona.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbopciona.setForeground(new java.awt.Color(0, 0, 204));
        jlbopciona.setText("A");
        jlbopciona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbopciona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbopcionaMouseClicked(evt);
            }
        });

        jtfopciond.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfopciond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfopciondActionPerformed(evt);
            }
        });

        jtfopcionc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfopcionc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfopcioncActionPerformed(evt);
            }
        });

        jtfopciona.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfopciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfopcionaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("¿Cuanto deseas aprender de la Biblia?");

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen2.png"))); // NOI18N

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ssssssssssssssssssssssss.jpg"))); // NOI18N
        panelImage4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelImage4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelImage4Layout = new javax.swing.GroupLayout(panelImage4);
        panelImage4.setLayout(panelImage4Layout);
        panelImage4Layout.setHorizontalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImage4Layout.setVerticalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aaaaaaaaaaaaaaaaaaaaaaaaaaa.jpg"))); // NOI18N
        panelImage5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelImage5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelImage5Layout = new javax.swing.GroupLayout(panelImage5);
        panelImage5.setLayout(panelImage5Layout);
        panelImage5Layout.setHorizontalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImage5Layout.setVerticalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel16.setText("12. Pablo");

        jLabel17.setText("10. Bartolome");

        jLabel18.setText("11. Judas Tadeo");

        jLabel19.setText("9. Andres");

        jLabel20.setText("8. Felipe");

        jLabel21.setText("7. Matias");

        jLabel22.setText("6. Jacobo");

        jLabel23.setText("5. Pedro");

        jLabel24.setText("4. Juan");

        jLabel25.setText("3. Lucas");

        jLabel26.setText("2. Marco");

        jLabel27.setText("1. Mateo");

        jLabel29.setText("13. Jesus de Nazaret");

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelShadow1Layout.createSequentialGroup()
                        .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel29))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addContainerGap())
        );

        panelImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gggggggggggggggggggggggggggggggggggggggggggggggggggggggggg.png"))); // NOI18N

        javax.swing.GroupLayout panelImage7Layout = new javax.swing.GroupLayout(panelImage7);
        panelImage7.setLayout(panelImage7Layout);
        panelImage7Layout.setHorizontalGroup(
            panelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        panelImage7Layout.setVerticalGroup(
            panelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelImage6Layout = new javax.swing.GroupLayout(panelImage6);
        panelImage6.setLayout(panelImage6Layout);
        panelImage6Layout.setHorizontalGroup(
            panelImage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelImage6Layout.setVerticalGroup(
            panelImage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage2Layout.createSequentialGroup()
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelImage2Layout.createSequentialGroup()
                        .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelImage2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelImage2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(panelImage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelImage2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(panelImage6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage2Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addGroup(panelImage2Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbopcionc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbopciona, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfopcionc, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfopciona, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage2Layout.createSequentialGroup()
                        .addComponent(jlbopcionb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfopcionb, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage2Layout.createSequentialGroup()
                        .addComponent(jlbopciond, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfopciond, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage2Layout.createSequentialGroup()
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelImage6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelImage2Layout.createSequentialGroup()
                            .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelImage2Layout.createSequentialGroup()
                                    .addComponent(panelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage2Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87)))
                            .addGap(143, 143, 143))
                        .addGroup(panelImage2Layout.createSequentialGroup()
                            .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlbopciona)
                                .addComponent(jtfopciona, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlbopcionb)
                                .addComponent(jtfopcionb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlbopcionc)
                                .addComponent(jtfopcionc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlbopciond)
                                .addComponent(jtfopciond, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(74, 74, 74)))
                    .addGroup(panelImage2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(panelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelImage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 704, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void verificar_respuesta(){
   
//int num_preguntas=palabras.size();
//contamos el numero de preguntas=13
    while (preguntas_a_mostrar.size()!=12) {
        //seleccionamos aleatoriamente las preguntas en array palabras
       if(opcion.equals("")){
        System.out.println("Error no hay nada");
       System.out.print(preguntas_a_mostrar.size());
       break;}
       else{
        if(preguntas_a_mostrar.size()==0){
        
        
        System.out.print(preguntas_a_mostrar.size());
        //String conf_resp=
        break;
        }
        else{
        }
    }
   
  
    }
}

public void subir_nivel() {
    // repone todos los labeles negros
    nivel++;
    for(javax.swing.JLabel label: niveles) {
        label.setForeground(Color.BLACK);
        //label.setBackground(Color.red);
    }
    niveles.get(nivel).setForeground(Color.WHITE);
}

public void llenar_label_niveles() {
    this.niveles.clear();
    niveles.add(jLabel27); // nivel 1
    niveles.add(jLabel26);
    niveles.add(jLabel25);
    niveles.add(jLabel24);
    niveles.add(jLabel23);
    niveles.add(jLabel22);
    niveles.add(jLabel21);
    niveles.add(jLabel20);
    niveles.add(jLabel19);
    niveles.add(jLabel17);
    niveles.add(jLabel18);
    niveles.add(jLabel16);
    niveles.add(jLabel29); // nivel 13
    
}

public void nueva_pregunta(){
    int n=0;
    
            Double indexPreguntaSeleccionada = (Math.random()*palabras.size());
            String pregunta_a_mostrar= palabras.get(indexPreguntaSeleccionada.intValue());
                      
           while(n==0){
            boolean comparar_pregunta=preguntas_a_mostrar.contains(pregunta_a_mostrar);
            if(comparar_pregunta==true){
               indexPreguntaSeleccionada = (Math.random()*palabras.size());
               pregunta_a_mostrar= palabras.get(indexPreguntaSeleccionada.intValue());
               n=0;
            }
            else{
                preguntas_a_mostrar.add(pregunta_a_mostrar);
                jLabel2.setOpaque(true);
                jLabel2.setBackground(new Color(0, 0,0));
                jLabel2.setText(pregunta_a_mostrar);
                jLabel2.setForeground(Color.white);
            String id_pregunta;
                try {
                   id_pregunta =db.Select2("tbl_preguntas", "*","tx_preguntas='"+pregunta_a_mostrar+"'").getString("id_preguntas");
                   jtfopciona.setText(db.Select2("tbl_resp_inc", "*", "id_preguntas='"+id_pregunta+"' AND opcion='a'").getString("resp_incorrecta"));
                   jtfopcionb.setText(db.Select2("tbl_resp_inc", "*", "id_preguntas='"+id_pregunta+"' AND opcion='b'").getString("resp_incorrecta"));
                   jtfopcionc.setText(db.Select2("tbl_resp_inc", "*", "id_preguntas='"+id_pregunta+"' AND opcion='c'").getString("resp_incorrecta"));
                   jtfopciond.setText(db.Select2("tbl_resp_inc", "*", "id_preguntas='"+id_pregunta+"' AND opcion='d'").getString("resp_incorrecta"));
                } catch (Exception e) {
                }
                
                System.out.print(preguntas_a_mostrar.size());
                n++;
        }   
           }
}

public boolean isRespuestaCorrecta(String respuesta) {
    String id_pregunta, respuesta_correcta;
        try {    
            id_pregunta =db.Select2("tbl_preguntas", "*","tx_preguntas='"+jLabel2.getText()+"'").getString("id_preguntas");
            respuesta_correcta=db.Select2("tbl_preguntas", "*","id_preguntas='"+id_pregunta+"'").getString("respuesta_correcta");
            System.out.println();
            if (respuesta_correcta.equals(respuesta)) return true;
        } catch (SQLException ex) {
            Logger.getLogger(gedeonario_preguntas.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
}    
        

public void confirmar_respuesta(){rt
    String id_pregunta,respuesta;
        try {
            id_pregunta =db.Select2("tbl_preguntas", "*","tx_preguntas='"+jLabel2.getText()+"'").getString("id_preguntas");
            respuesta=db.Select2("tbl_preguntas", "*","id_preguntas='"+id_pregunta+"'").getString("respuesta_correcta");
        if(respuesta.equals(opcion)){
            JOptionPane.showMessageDialog(null, "Respuesta Correcta");
            System.out.println(opcion);
            System.out.println(respuesta);
            opcion="";
            if(cp==13){
                JOptionPane.showMessageDialog(null, "FELICIDADES HAZ GANADO EL JUEGO...YA ERES UN GEDEON"); 
                 this.dispose();
                gedeonario geo=new gedeonario();
                geo.setVisible(true);
            }else{
                this.subir_nivel();
                nueva_pregunta();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Respuesta Incorrecta, usted Perdio");
            this.dispose();
            gedeonario geo=new gedeonario();
            geo.setVisible(true);
            geo.setVisible(false);
             System.out.println(opcion);
            System.out.println(respuesta);
        }
        }
        catch (SQLException ex) {
            Logger.getLogger(gedeonario_preguntas.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void cargar_primera_pregunta(){
Double indexPreguntaSeleccionada = (Math.random()*palabras.size());
        String pregunta_a_mostrar= palabras.get(indexPreguntaSeleccionada.intValue());
        preguntas_a_mostrar.add(pregunta_a_mostrar);
        jLabel2.setOpaque(true);
        jLabel2.setBackground(new Color(0, 0,0));
        jLabel2.setText(pregunta_a_mostrar);
        jLabel2.setForeground(Color.white);
        String id_pregunta;
            try {
               id_pregunta =db.Select2("tbl_preguntas", "*","tx_preguntas='"+pregunta_a_mostrar+"'").getString("id_preguntas");
               jtfopciona.setText(db.Select2("tbl_resp_inc", "*", "id_preguntas='"+id_pregunta+"' AND opcion='a'").getString("resp_incorrecta"));
               jtfopcionb.setText(db.Select2("tbl_resp_inc", "*", "id_preguntas='"+id_pregunta+"' AND opcion='b'").getString("resp_incorrecta"));
               jtfopcionc.setText(db.Select2("tbl_resp_inc", "*", "id_preguntas='"+id_pregunta+"' AND opcion='c'").getString("resp_incorrecta"));
               jtfopciond.setText(db.Select2("tbl_resp_inc", "*", "id_preguntas='"+id_pregunta+"' AND opcion='d'").getString("resp_incorrecta"));
            } catch (Exception e) {
            }
            //jLabel27.setText("Judas");
            //jLabel26.setForeground(Color.WHITE);
            //jLabel27.setBackground(Color.red);
}
    private void jtfopcionbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfopcionbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfopcionbActionPerformed

    private void jlbopcioncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbopcioncMouseClicked
     
        if( JOptionPane.showConfirmDialog(rootPane, "¿Respuesta Definitiva?","Confirmación", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
          opcion=jtfopcionc.getText();
         confirmar_respuesta();
      }else{
         System.out.print("cancelado"); 
      } // TODO add your handling code here:
    }//GEN-LAST:event_jlbopcioncMouseClicked

    private void jlbopcionbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbopcionbMouseClicked
      
        
        if( JOptionPane.showConfirmDialog(rootPane, "¿Respuesta Definitiva?","Confirmación", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        opcion=jtfopcionb.getText();
         confirmar_respuesta();
      }else{
         System.out.print("cancelado"); 
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbopcionbMouseClicked

    private void jlbopciondMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbopciondMouseClicked
     
        
        if( JOptionPane.showConfirmDialog(rootPane, "¿Respuesta Definitiva?","Confirmación", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        opcion=jtfopciond.getText();
            confirmar_respuesta();
      }else{
         System.out.print("cancelado"); 
      }// TODO add your handling code here:
    }//GEN-LAST:event_jlbopciondMouseClicked

    private void jlbopcionaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbopcionaMouseClicked
   
      
        if( JOptionPane.showConfirmDialog(rootPane, "¿Respuesta Definitiva?","Confirmación", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            opcion=jtfopciona.getText();
            confirmar_respuesta();
      }else{
            System.out.print("cancelado"); 
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbopcionaMouseClicked

    private void jtfopciondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfopciondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfopciondActionPerformed

    private void jtfopcioncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfopcioncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfopcioncActionPerformed

    private void jtfopcionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfopcionaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfopcionaActionPerformed

    private void panelImage5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelImage5MouseClicked
        if(comdin==0){
            comdin = 1;
            Timer timer = new Timer (1000, new ActionListener () 
            { 
                boolean ejecutar = true;
                biblia_interactiva ven;
                public void actionPerformed(ActionEvent e) 
                { 
                    if (ejecutar) {
                        ejecutar = false;
                        abrirVentana();
                    }
                    
                    if (!ven.decontar()) {
                        ven.setVisible(false);
                        ((Timer)e.getSource()).stop();
                    }
                   
                 } 
                public void abrirVentana() {
                    ven = new biblia_interactiva();
                    ven.setVisible(true);
                }
                
            }); 
            timer.start();
        }
        // TODO add your handling code here:

    }//GEN-LAST:event_panelImage5MouseClicked

    private void panelImage4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelImage4MouseClicked
        // Eliminar dos respuestas incorrectas
        if (this.comdin2) {
            this.comdin2 = false;
            ArrayList <javax.swing.JTextField> opciones = new ArrayList<javax.swing.JTextField>();
            opciones.add(this.jtfopciona);
            opciones.add(this.jtfopcionb);
            opciones.add(this.jtfopcionc);
            opciones.add(this.jtfopciond);

            int r = 0;
            Double rr = 0.0;
            while(opciones.size() != 2) {

                rr = Math.random()*opciones.size()-1;
                r = rr.intValue();
                System.out.println("rr:"+rr+", r:"+r+", size:"+opciones.size());
                if (!this.isRespuestaCorrecta(opciones.get(r).getText())) {
                    opciones.get(r).setText("");
                    opciones.remove(r);
                }
            }
        }
    }//GEN-LAST:event_panelImage4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gedeonario_preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gedeonario_preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gedeonario_preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gedeonario_preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gedeonario_preguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jlbopciona;
    private javax.swing.JLabel jlbopcionb;
    private javax.swing.JLabel jlbopcionc;
    private javax.swing.JLabel jlbopciond;
    private javax.swing.JTextField jtfopciona;
    private javax.swing.JTextField jtfopcionb;
    private javax.swing.JTextField jtfopcionc;
    private javax.swing.JTextField jtfopciond;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private org.edisoncor.gui.panel.PanelImage panelImage5;
    private org.edisoncor.gui.panel.PanelImage panelImage6;
    private org.edisoncor.gui.panel.PanelImage panelImage7;
    private org.edisoncor.gui.panel.PanelShadow panelShadow1;
    // End of variables declaration//GEN-END:variables
}
