/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gedeon1;

import java.awt.event.KeyEvent;

/**
 *
 * @author usuario
 */
public class etapa1 extends javax.swing.JFrame {

    /**
     * Creates new form etapa1
     */
    public etapa1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        compositeEffect1 = new com.sun.animation.effects.CompositeEffect();
        compositeEffect2 = new com.sun.animation.effects.CompositeEffect();
        compositeEffect3 = new com.sun.animation.effects.CompositeEffect();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        labelHeader1 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader3 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader4 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader5 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader6 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader7 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader8 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader9 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader10 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader12 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader13 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader14 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader15 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader16 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader17 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader18 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader19 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader20 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader21 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader22 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader23 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader24 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader25 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader26 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader27 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader28 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader29 = new org.edisoncor.gui.label.LabelHeader();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gedeon.jpg"))); // NOI18N

        labelHeader1.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader1.setText("A");
        labelHeader1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader3.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader3.setText("W");
        labelHeader3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader4.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader4.setText("L");
        labelHeader4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader5.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader5.setText("B");
        labelHeader5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader6.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader6.setText("K");
        labelHeader6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader7.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader7.setText("C");
        labelHeader7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader8.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader8.setText("Y");
        labelHeader8.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader9.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader9.setText("M");
        labelHeader9.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader10.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader10.setText("E");
        labelHeader10.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader12.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader12.setText("N");
        labelHeader12.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader13.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader13.setText("U");
        labelHeader13.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader14.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader14.setText("F");
        labelHeader14.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader15.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader15.setText("P");
        labelHeader15.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader16.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader16.setText("Ñ");
        labelHeader16.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader17.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader17.setText("X");
        labelHeader17.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader18.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader18.setText("S");
        labelHeader18.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader19.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader19.setText("O");
        labelHeader19.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader20.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader20.setText("R");
        labelHeader20.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader21.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader21.setText("T");
        labelHeader21.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader22.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader22.setText("V");
        labelHeader22.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader23.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader23.setText("G");
        labelHeader23.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader24.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader24.setText("D");
        labelHeader24.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader25.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader25.setText("I");
        labelHeader25.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader26.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader26.setText("Z");
        labelHeader26.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader27.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader27.setText("Q");
        labelHeader27.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader28.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader28.setText("H");
        labelHeader28.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelHeader29.setBackground(new java.awt.Color(255, 255, 51));
        labelHeader29.setText("J");
        labelHeader29.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(labelHeader18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader26, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelHeader6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelHeader4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(labelHeader9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader27, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader24, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader28, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHeader25, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelHeader29, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(507, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(466, 466, 466))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader23, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader28, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader29, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHeader6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader27, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHeader21, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader17, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader26, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeader18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 203, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(etapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(etapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(etapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(etapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new etapa1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sun.animation.effects.CompositeEffect compositeEffect1;
    private com.sun.animation.effects.CompositeEffect compositeEffect2;
    private com.sun.animation.effects.CompositeEffect compositeEffect3;
    private javax.swing.JTextField jTextField1;
    private org.edisoncor.gui.label.LabelHeader labelHeader1;
    private org.edisoncor.gui.label.LabelHeader labelHeader10;
    private org.edisoncor.gui.label.LabelHeader labelHeader12;
    private org.edisoncor.gui.label.LabelHeader labelHeader13;
    private org.edisoncor.gui.label.LabelHeader labelHeader14;
    private org.edisoncor.gui.label.LabelHeader labelHeader15;
    private org.edisoncor.gui.label.LabelHeader labelHeader16;
    private org.edisoncor.gui.label.LabelHeader labelHeader17;
    private org.edisoncor.gui.label.LabelHeader labelHeader18;
    private org.edisoncor.gui.label.LabelHeader labelHeader19;
    private org.edisoncor.gui.label.LabelHeader labelHeader20;
    private org.edisoncor.gui.label.LabelHeader labelHeader21;
    private org.edisoncor.gui.label.LabelHeader labelHeader22;
    private org.edisoncor.gui.label.LabelHeader labelHeader23;
    private org.edisoncor.gui.label.LabelHeader labelHeader24;
    private org.edisoncor.gui.label.LabelHeader labelHeader25;
    private org.edisoncor.gui.label.LabelHeader labelHeader26;
    private org.edisoncor.gui.label.LabelHeader labelHeader27;
    private org.edisoncor.gui.label.LabelHeader labelHeader28;
    private org.edisoncor.gui.label.LabelHeader labelHeader29;
    private org.edisoncor.gui.label.LabelHeader labelHeader3;
    private org.edisoncor.gui.label.LabelHeader labelHeader4;
    private org.edisoncor.gui.label.LabelHeader labelHeader5;
    private org.edisoncor.gui.label.LabelHeader labelHeader6;
    private org.edisoncor.gui.label.LabelHeader labelHeader7;
    private org.edisoncor.gui.label.LabelHeader labelHeader8;
    private org.edisoncor.gui.label.LabelHeader labelHeader9;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
