/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bd_avanzada;

import java.awt.Color;
import java.awt.Event;
import java.awt.Panel;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author BERLIN COELLO
 */
public class Usuario_reg extends javax.swing.JFrame {
ManejadorSQL m;
    Archivos a;
    String[] lineas;
    /**
     * Creates new form Usuario_reg
     */
    public Usuario_reg(ManejadorSQL m3) {
        try {
            m=m3;
            initComponents();
            String c_est,c_mun,c_ciu;
            String []datos = new String [2];
            this.setLocationRelativeTo(null);
            a = new Archivos();
            inhabilitaPegar(u_nombre);
            inhabilitaPegar(u_apellido);
            inhabilitaPegar(u_login);
            inhabilitaPegar(u_cedula);
            inhabilitaPegar(u_celular);
            inhabilitaPegar(u_telefono);
            inhabilitaPegar(u_calle);
            inhabilitaPegar(u_sector);
            inhabilitaPegar(u_parroquia);
            inhabilitaPegar(u_contrasena);
            inhabilitaPegar(u_rep_contras);
            inhabilitaPegar(u_pregunta);
            inhabilitaPegar(u_respuesta);
            inhabilitaPegar(u_rol);
            rellenar_pregunta();
            SLetras(u_nombre);
            SLetras(u_apellido);
            SLetras(u_parroquia);
            SLetras(u_sector);
            SLetras(u_respuesta);
            SNumeros(u_celular);
            SNumeros(u_telefono);
            SNumeros(u_codigo_postal);
            
            
            
            lineas = new String[9];
            lineas = a.Leer();
           // m = new ManejadorSQL(lineas[2], lineas[1], lineas[3], lineas[4], lineas[5], lineas[7], lineas[6]);
            m.setLineas(lineas);
            ResultSet b_esta=m.Select("tblsit_estado", "id_estado,nb_estado");//Seleccionamos los estados para el combo box
           while(b_esta.next()){
                datos[0]=b_esta.getString(1);
                datos[1]=b_esta.getString(2);
                u_c_estado.addItem(datos[1]); // agregamos los estados
                //System.out.println(datos[0]);
            }
           
            {
           }
        } catch (Exception ex) {
            Logger.getLogger(Usuario_reg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        most_e = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        u_nombre = new javax.swing.JTextField();
        u_apellido = new javax.swing.JTextField();
        u_login = new javax.swing.JTextField();
        u_cedula = new javax.swing.JTextField();
        u_celular = new javax.swing.JTextField();
        u_calle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        most_e2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        u_sector = new javax.swing.JTextField();
        u_parroquia = new javax.swing.JTextField();
        u_c_municipio = new javax.swing.JComboBox();
        u_c_estado = new javax.swing.JComboBox();
        u_codigo_postal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        u_telefono = new javax.swing.JTextField();
        c_cel = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        u_contrasena = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        most_e1 = new javax.swing.JLabel();
        u_rep_contras = new javax.swing.JPasswordField();
        u_pregunta = new javax.swing.JComboBox();
        u_respuesta = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        u_c_tipo = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        u_rol = new javax.swing.JComboBox();
        u_c_ciudad = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Usuario");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");

        jButton2.setText("Cancelar");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cedula/Rif");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Telefono Celular");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Apellido");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sector/Urbanización");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Calle/Avenida");

        u_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_nombreKeyTyped(evt);
            }
        });

        u_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_apellidoKeyTyped(evt);
            }
        });

        u_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_loginKeyTyped(evt);
            }
        });

        u_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_cedulaKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Dirección");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Datos Personales");

        most_e2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Parroquia");

        u_c_municipio.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        u_c_municipio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Municipio" }));
        u_c_municipio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                u_c_municipioItemStateChanged(evt);
            }
        });
        u_c_municipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_c_municipioActionPerformed(evt);
            }
        });

        u_c_estado.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        u_c_estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estado" }));
        u_c_estado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u_c_estadoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                u_c_estadoMousePressed(evt);
            }
        });
        u_c_estado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                u_c_estadoItemStateChanged(evt);
            }
        });
        u_c_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_c_estadoActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Código Postal");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Telefono de Casa");

        c_cel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0416", "0426", "0414", "0424", "0412" }));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Contraseña");

        u_contrasena.setText("jPasswordField1");
        u_contrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u_contrasenaMouseClicked(evt);
            }
        });
        u_contrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_contrasenaKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Seguridad al máximo");

        u_rep_contras.setText("jPasswordField1");
        u_rep_contras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u_rep_contrasMouseClicked(evt);
            }
        });

        u_pregunta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "¿Amigo de la Infancia?", "¿Colegio de Primaria?", "¿Nombre de su Mascota?", "¿Comida Favorita?", "¿Canción Favorita?" }));
        u_pregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_preguntaActionPerformed(evt);
            }
        });

        u_respuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_respuestaActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Tu Respuesta ");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Pregunta Secreta");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Repetir Contraseña");

        u_c_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sector", "Urbanización" }));

        label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Rol de Usuario");

        u_rol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Administrador", "Usuario Común" }));

        u_c_ciudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ciudad" }));
        u_c_ciudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                u_c_ciudadItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(u_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(u_cedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u_nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u_apellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(138, 138, 138))
            .addComponent(most_e2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(most_e, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(most_e1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(62, 62, 62)
                        .addComponent(u_c_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(u_sector, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(u_c_ciudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(u_c_estado, 0, 201, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(u_calle, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(u_parroquia, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(u_codigo_postal)
                                    .addComponent(u_c_municipio, 0, 189, Short.MAX_VALUE))
                                .addGap(103, 103, 103)))))
                .addGap(40, 40, 40))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(u_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(c_cel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addComponent(u_rep_contras, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(81, 81, 81)
                            .addComponent(u_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel21)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(61, 61, 61)))))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(u_respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u_pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButton1)
                        .addGap(115, 115, 115)
                        .addComponent(jButton2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(most_e, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(u_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_login, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(u_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(c_cel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(u_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(most_e2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(u_calle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(u_c_tipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(u_sector, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(u_parroquia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_c_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(u_c_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_c_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(u_codigo_postal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(most_e1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u_pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(u_respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(u_rep_contras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(u_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String u_nom,u_ape,u_log,u_ced,u_cel,u_c_cel,u_cal,u_sec,u_par,u_ciu,u_mun,u_est,u_c_pos,u_con,u_r_con,u_res,u_pre,u_rl;
u_nom=u_nombre.getText();
u_ape=u_apellido.getText();
u_log=u_login.getText();
u_ced=u_cedula.getText();
u_cel=u_celular.getText();
u_c_cel=c_cel.getSelectedItem().toString();
u_cal=u_calle.getText();
u_sec=u_sector.getText();
u_par=u_parroquia.getText();
u_ciu=u_c_ciudad.getSelectedItem().toString();
u_mun=u_c_municipio.getSelectedItem().toString();
u_est=u_c_estado.getSelectedItem().toString();
u_c_pos=u_codigo_postal.getText();
u_con=u_contrasena.getText();
u_res=u_respuesta.getText();
u_r_con=u_rep_contras.getText();
u_rl=u_rol.getSelectedItem().toString();
u_pre=u_pregunta.getSelectedItem().toString();
if(u_nom.equals("")||u_ape.equals("")||u_log.equals("")||u_ced.equals("")||u_cel.equals("")||u_cal.equals("")||u_c_cel.equals("")||u_sec.equals("")||u_mun.equals("Municipio")||u_ciu.equals("Ciudad")||u_est.equals("Estado")||u_c_pos.equals("")||u_con.equals("")||u_r_con.equals("")||u_res.equals("")||u_pre.equals("Seleccione")||u_rl.equals("Seleccione")){
mostrar_e("Debe llenar todos los campos");
}
else{
boolean resul = m.Select3("usuario", "tx_login", "tx_login='" + u_log+ "'");
            if (resul == true) {
                mostrar_e("Error, El login solicitado no está disponible, intente con Otro ");
            }
            else{
                if(!u_con.equals(u_r_con)){
                
               mostrar_e("Las Contraseñas ingresadas no coinciden. Por favor verifique");           
                
                }
                else{
                     boolean ing_u = false;
                    boolean ing_dire = false;
                    boolean ing_tele = false;
                    boolean ing_status = false;
                    //ing_dire = m.Insert("direccion", "tx_urbanizacion_sector,tx_calle_avenida,tx_parroquia, tx_nombre_u_s", "'" + u_sec + "','" + u_cal + "','" + u_par + "','" + u_ns + "'");
                    ing_status = m.Insert("status", "nom_status,tx_status", "'" + u_nom + "','" + "Activo" + "'");
                    ing_tele = m.Insert("telefono", "num_tlf,tx_tipo", "'" + u_cel + "','" + u_c_cel + "'");
//ing_tele=m.Insert("telefono", "id_tlf,id_usuario,num_tlf,tx_tipo,id_integrantes", "'"+"','"+"'"+u_cel+"','"+2+"[");
                    try {
                        //consulta de la ciudad el idt
                        String id_ciudad = m.Select2("tblsit_ciudad", "*", "nb_ciudad='" + u_ciu + "'").getString("id_ciudad");
                        System.out.print(id_ciudad);
                        ing_dire = m.Insert("direccion", "tx_urbanizacion_sector,tx_calle_avenida,tx_parroquia, tx_nombre_u_s,id_ciudad", "'" + u_sec + "','" + u_cal + "','" + u_par + "','" + u_sec + "','" + id_ciudad + "'");
                        String id_dire = m.Select2("direccion", "*", "id_ciudad='" + id_ciudad + "'").getString("id_direccion");
String status = m.Select2("status", "*", "nom_status='" + u_nom + "'").getString("id_status");
//                        System.out.print(id_tlf);
                        String id_tlf = m.Select2("telefono", "*", "num_tlf='" + u_cel + "'").getString("id_tlf");
                        System.out.print(id_tlf);
                        ing_u = m.Insert("usuario", "tx_nombre,tx_apellido,tx_login,tx_clave,ci_rif,id_direccion,id_status", "'" + u_nom + "','" + u_ape + "','" + u_log + "','" + u_con + "','" + u_ced + "','" + id_dire + "','" + status + "'");

                        //String id_u=m.Select2("usuario", "*","tx_nombre='"+u_nomb+"'").getString("id_usuario");
                        //System.out.print(id_u);   //String id_ciu = m.Select("tblsit_ciudad", "id_ciudad","nb_ciudad='" + u_ciu + "'").getString("id_ciudad");
                        //ing_dire=m.Insert("direcion", "tx_urbanizacion_sector,tx_calle_avenida,tx_parroquia,tx_nombre_u_s",u_sec+"','"+u_cal+"'"+u_par+"'");
                        // cargar_ciudad(id_ciu);
                    } catch (SQLException ex) {
                        Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    if (ing_status = true) {
                        mostrar_e("Registrado");
                    } else {
                        mostrar_e("Error");
                    }
                    //ing_u=m.Insert("usuario", "", u_res)
                    //mostrar_e("Correcto");
                    //}// catch (SQLException ex) {
                    // Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                    // }
                
                }
            }
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
public void mostrar_e(String e){
    most_e.setAlignmentY(CENTER_ALIGNMENT);
            most_e.setHorizontalAlignment(WIDTH / 2);
            most_e.setAlignmentX(CENTER_ALIGNMENT);
            most_e.setText(e);
            most_e.setForeground(Color.red);
           most_e1.setAlignmentY(CENTER_ALIGNMENT);
            most_e1.setHorizontalAlignment(WIDTH / 2);
            most_e1.setAlignmentX(CENTER_ALIGNMENT);
            most_e1.setText(e);
            most_e1.setForeground(Color.red);
             most_e2.setAlignmentY(CENTER_ALIGNMENT);
            most_e2.setHorizontalAlignment(WIDTH / 2);
            most_e2.setAlignmentX(CENTER_ALIGNMENT);
            most_e2.setText(e);
            most_e2.setForeground(Color.red);
}
    private void u_respuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_respuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_respuestaActionPerformed

    private void u_contrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_contrasenaMouseClicked
u_contrasena.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_u_contrasenaMouseClicked

    private void u_rep_contrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_rep_contrasMouseClicked
u_rep_contras.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_u_rep_contrasMouseClicked

    private void u_c_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_c_estadoActionPerformed
      // u_c_estado.removeItem("Estado"); // TODO add your handling code here:
        //if()
    }//GEN-LAST:event_u_c_estadoActionPerformed

    private void u_c_estadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_c_estadoMousePressed
//u_c_estado.removeItem("Estado");        // TODO add your handling code here:
    }//GEN-LAST:event_u_c_estadoMousePressed

    private void u_c_estadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_c_estadoMouseClicked
       u_c_estado.removeItem("Estado");  // TODO add your handling code here:
    }//GEN-LAST:event_u_c_estadoMouseClicked

    private void u_c_estadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_u_c_estadoItemStateChanged
  String c_est,c_mun,c_ciu;
     String seleccion =u_c_estado.getSelectedItem().toString();
            if (!seleccion.equals("Estado")) {
              
                try {

                    String id = m.Select2("tblsit_estado", "id_estado", "nb_estado='" + seleccion + "'").getString("id_estado");
                    cargar_municipio(id);

                } catch (SQLException ex) {
                    Logger.getLogger(Usuario_reg.class.getName()).log(Level.SEVERE, null, ex);
                }

            }        // TODO add your handling code here:
    }//GEN-LAST:event_u_c_estadoItemStateChanged

    private void u_c_municipioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_u_c_municipioItemStateChanged
    String seleccion = u_c_municipio.getSelectedItem().toString();
        if (!seleccion.equals("Municipio")) {
            try {
String idm=m.Select2("tblsit_municipio","id_municipio","nb_municipio='"+ seleccion + "'").getString("id_municipio"); // voy aqui
              cargar_ciudad(idm); 

            } catch (SQLException ex) {
                Logger.getLogger(Usuario_reg.class.getName()).log(Level.SEVERE, null, ex);
            } }   // TODO add your handling code here:
    }//GEN-LAST:event_u_c_municipioItemStateChanged
static void inhabilitaPegar(JComponent campo) {

InputMap map = campo.getInputMap();
map.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
map.put(KeyStroke.getKeyStroke(KeyEvent.VK_INSERT, Event.SHIFT_MASK), "null");
}

public void SLetras(JTextField a){
a.addKeyListener(new KeyAdapter() {
public void keyTyped(KeyEvent e){
char c=e.getKeyChar();
if(Character.isDigit(c)){
    getToolkit().beep();
e.consume();
}
}
});
}
public void SNumeros(JTextField a){
a.addKeyListener(new KeyAdapter() {
public void keyTyped(KeyEvent e){
char c=e.getKeyChar();
if(!Character.isDigit(c)){
    getToolkit().beep();
e.consume();
}
}
});
}
    private void u_c_municipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_c_municipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_c_municipioActionPerformed

    private void u_c_ciudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_u_c_ciudadItemStateChanged
      // TODO add your handling code here:
    }//GEN-LAST:event_u_c_ciudadItemStateChanged

    private void u_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_nombreKeyTyped
if(u_nombre.getText().length()>=20){
          evt.consume();
          getToolkit().beep();
      }  
// TODO add your handling code here:
    }//GEN-LAST:event_u_nombreKeyTyped

    private void u_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_apellidoKeyTyped
if(u_apellido.getText().length()>=20){
          evt.consume();
          getToolkit().beep();
      }         // TODO add your handling code here:
    }//GEN-LAST:event_u_apellidoKeyTyped

    private void u_loginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_loginKeyTyped
if(u_login.getText().length()>=60){
          evt.consume();
          getToolkit().beep();
      }         // TODO add your handling code here:
    }//GEN-LAST:event_u_loginKeyTyped

    private void u_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_cedulaKeyTyped
       if(u_cedula.getText().length()>=12){
          evt.consume();
          getToolkit().beep();
      }  // TODO add your handling code here:
    }//GEN-LAST:event_u_cedulaKeyTyped

    private void u_contrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_contrasenaKeyTyped
if(u_contrasena.getText().length()>=50){
          evt.consume();
          getToolkit().beep();
      }         // TODO add your handling code here:
    }//GEN-LAST:event_u_contrasenaKeyTyped
public void rellenar_pregunta(){
    try{
 DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
            //DriverManager.getConnection("jdbc:postgresql://localhost/dbsitxian", "importadoraxian", "sitvenpfi");
            ResultSet rs =m.Select("preguntas", "id_pregunta,tx_pregunta");
            u_pregunta.removeAllItems();
            modeloCombo.addElement("Seleccione");
            while (rs.next()) {
                modeloCombo.addElement(rs.getObject("tx_pregunta"));
            }
            rs.close();
            u_pregunta.setModel(modeloCombo);
        } catch (SQLException ex) {
            Logger.getLogger(recuperar_contra.class.getName()).log(Level.SEVERE, null, ex);
        } 
  

    }

    private void u_preguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_preguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_preguntaActionPerformed
public void cargar_ciudad(String idm) {
        try {
            DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
            try (ResultSet rs = m.Select("tblsit_ciudad", "*", "id_municipio='" + idm + "'")) {
                while (rs.next()) {
                    modeloCombo.addElement(rs.getObject("nb_ciudad"));
                }
            }
            u_c_ciudad.setModel(modeloCombo);
        } catch (SQLException ex) {
            Logger.getLogger(Usuario_reg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    public void cargar_municipio(String id){
try {

            DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
           // Class.forName(lineas[5]);
           
            ResultSet rs =m.Select("tblsit_municipio", "*", "id_estado='" + id + "'");
            while (rs.next()) {
                modeloCombo.addElement(rs.getObject("nb_municipio"));
            }
            rs.close();
            u_c_municipio.setModel(modeloCombo);
        } catch (SQLException ex) {
            Logger.getLogger(Usuario_reg.class.getName()).log(Level.SEVERE, null, ex);
        }// catch (ClassNotFoundException ex) {
          //  Logger.getLogger(Usuario_reg.class.getName()).log(Level.SEVERE, null, ex);
        //} Brother esto no se pa q es de pananaaaaaderia
}
    /**
     * @param args the command line arguments
     */
    public  void main(ManejadorSQL m3) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario_reg(m).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c_cel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel most_e;
    private javax.swing.JLabel most_e1;
    private javax.swing.JLabel most_e2;
    private javax.swing.JTextField u_apellido;
    private javax.swing.JComboBox u_c_ciudad;
    private javax.swing.JComboBox u_c_estado;
    private javax.swing.JComboBox u_c_municipio;
    private javax.swing.JComboBox u_c_tipo;
    private javax.swing.JTextField u_calle;
    private javax.swing.JTextField u_cedula;
    private javax.swing.JTextField u_celular;
    private javax.swing.JTextField u_codigo_postal;
    private javax.swing.JPasswordField u_contrasena;
    private javax.swing.JTextField u_login;
    private javax.swing.JTextField u_nombre;
    private javax.swing.JTextField u_parroquia;
    private javax.swing.JComboBox u_pregunta;
    private javax.swing.JPasswordField u_rep_contras;
    private javax.swing.JTextField u_respuesta;
    private javax.swing.JComboBox u_rol;
    private javax.swing.JTextField u_sector;
    private javax.swing.JTextField u_telefono;
    // End of variables declaration//GEN-END:variables
}
