/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gedeon1;

import base_dato.ManejadorSQL;
import base_dato.validaciones;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import millonario.biblia_interactiva;
 
public class inicio extends javax.swing.JFrame {
 ManejadorSQL m;
 validaciones v = new validaciones();
 int equivoco=0, int_bloqueo;
    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        // icono
        ImageIcon img = new ImageIcon(getClass().getResource(Gedeon1.icono));
        this.setIconImage(img.getImage());
   
        mensaje.setVisible(false);
        validaciones v = new validaciones();
        m = new ManejadorSQL("postgres", "localhost", "freddy", "1234", "org.postgresql.Driver", "5432", "jdbc:postgresql", "2", v);
        usuario.setEditable(true);
        usuario.setVisible(true);
         this.setLocationRelativeTo(null);
     try {
          int_bloqueo =m.Select2("tbl_conf_clave", "intentos", "activo='1'").getInt("intentos");

//esta linea posiciona la ventana en el centro de la pantalla
         //Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();//para que la ventana aparezca maximizada
         //this.setSize(screenSize);
     } catch (SQLException ex) {
         Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
     }
}

    public void restablecerCampos() {
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        titulo = new javax.swing.JLabel();
        nombre_usuario = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        nombre_clave = new javax.swing.JLabel();
        clave = new javax.swing.JPasswordField();
        salir = new javax.swing.JButton();
        boton_aceptar = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gedeon");
        setUndecorated(true);
        setResizable(false);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj.jpg"))); // NOI18N

        titulo.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 0, 0));
        titulo.setText("GEDEON");

        nombre_usuario.setBackground(new java.awt.Color(255, 51, 51));
        nombre_usuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombre_usuario.setForeground(new java.awt.Color(255, 204, 51));
        nombre_usuario.setText("Usuario:");

        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usuarioKeyTyped(evt);
            }
        });

        nombre_clave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombre_clave.setForeground(new java.awt.Color(255, 204, 51));
        nombre_clave.setText("Contraseña:");

        clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salir.setForeground(new java.awt.Color(0, 51, 204));
        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        boton_aceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_aceptar.setForeground(new java.awt.Color(0, 51, 204));
        boton_aceptar.setText("Aceptar");
        boton_aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_aceptarMouseClicked(evt);
            }
        });
        boton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_aceptarActionPerformed(evt);
            }
        });

        mensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mensaje.setText("jLabel1");

        titulo1.setFont(new java.awt.Font("Serif", 2, 48)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 0, 0));
        titulo1.setText("Juego Biblico Interactivo");

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lock.png"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel2.setForeground(new java.awt.Color(204, 255, 51));
        jLabel2.setText("Autor:");

        jLabel3.setForeground(new java.awt.Color(204, 255, 51));

        jLabel4.setForeground(new java.awt.Color(204, 255, 51));

        jLabel5.setForeground(new java.awt.Color(204, 255, 51));
        jLabel5.setText("Laguna Freddy J.");

        jButton1.setText("Recuperar contraseña");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelImage1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelImage1Layout.createSequentialGroup()
                                    .addComponent(nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(69, 69, 69)
                                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelImage1Layout.createSequentialGroup()
                                    .addComponent(nombre_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(panelImage1Layout.createSequentialGroup()
                                            .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(43, 43, 43)
                                            .addComponent(boton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(mensaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombre_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(mensaje)
                        .addGap(87, 87, 87)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        
    }//GEN-LAST:event_salirMouseClicked

    private void boton_aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_aceptarMouseClicked
        
    }//GEN-LAST:event_boton_aceptarMouseClicked
    public void mostrar_mensaje(String mensaje1){
       mensaje.setText(mensaje1);        
    }
    public void bloquear_campos(){
        usuario.setEditable(false);
        clave.setEditable(false);
        boton_aceptar.setEnabled(false);
        usuario.setText("");
        clave.setText("");
        salir.setEnabled(false);

    }
    public void desbloquear(){
        usuario.setEditable(true);
        clave.setEditable(true);
        boton_aceptar.setEnabled(true);
        salir.setEnabled(true);
    }

    private void boton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_aceptarActionPerformed
        String estatus, usr, clv;
        
        usr = usuario.getText();
        clv = clave.getText();

        if (usr.equals("") || clv.equals("")) {
            mensaje.setVisible(true);
            mensaje.setText("Todos los campos deben estar llenos");
            mensaje.setForeground(Color.RED);
        } else {
            
            boolean existe = m.Select3("usuarios", "*", "tx_login='" + usr + "' and clave='" + m.getStringMessageDigest(clv, "md5") + "'");
            if (existe == true) {
                
                try {
                    int id_rol = m.Select2("usuarios", "*", "tx_login='" + usr + "' and clave='" + m.getStringMessageDigest(clv, "md5") + "'").getInt("id_rol_usr");
                    estatus=m.Select2("usuarios", "*", "tx_login='" + usr + "' and clave='" + m.getStringMessageDigest(clv, "md5") + "'").getString("id_estatus");
                    String nb_estatus=m.Select2("tbl_estatus", "*", "id_estatus='" + estatus + "'").getString("nb_estatus");
                    if(nb_estatus.equals("inactivo")){
                        JOptionPane.showMessageDialog(null , "Su cuenta en el sistema a si desacctivada, comuniquese con su profesor");
                        usuario.setText("");
                        clave.setText("");
                        mensaje.setVisible(false);
                        
                    }else{
                    
                        String id_usuario = m.Select2("usuarios", "*", "tx_login='" + usr + "' and clave='" + m.getStringMessageDigest(clv, "md5") + "'").getString("id_usuario");
                        
                        m.id_usuario=id_usuario;
                        Gedeon1.id_usuario=Integer.parseInt(id_usuario);
                        int id_admin, id_estu, id_maestro;
                        id_admin = m.Select2("tbl_rol_usr", "*", "nb_rol_usr='Administrador'").getInt("id_rol_usr");
                        id_estu = m.Select2("tbl_rol_usr", "*", "nb_rol_usr='Estudiante'").getInt("id_rol_usr");
                        id_maestro = m.Select2("tbl_rol_usr", "*", "nb_rol_usr='Maestro'").getInt("id_rol_usr");
                        String id_est_admin, id_est_estu, id_est_maestro, nb_est_admin, nb_est_estu,nb_est_maestro;
                            id_est_admin = m.Select2("tbl_rol_usr", "*", "nb_rol_usr='Administrador'").getString("id_estatus");
                        id_est_estu = m.Select2("tbl_rol_usr", "*", "nb_rol_usr='Estudiante'").getString("id_estatus");
                        id_est_maestro = m.Select2("tbl_rol_usr", "*", "nb_rol_usr='Maestro'").getString("id_estatus");
                        nb_est_admin=m.Select2("tbl_estatus", "*", "id_estatus='" + id_est_admin + "'").getString("nb_estatus");
                        nb_est_estu=m.Select2("tbl_estatus", "*", "id_estatus='" + id_est_estu + "'").getString("nb_estatus");
                        nb_est_maestro=m.Select2("tbl_estatus", "*", "id_estatus='" + id_est_maestro + "'").getString("nb_estatus");
                          
                        if(nb_est_admin.equals("inactivo")&&id_rol==id_admin){
                        JOptionPane.showMessageDialog(null , "Se ha negado el accseso a los usuarios de tipo administrador");   
                        }else if(nb_est_maestro.equals("inactivo")&&id_rol==id_maestro){
                            JOptionPane.showMessageDialog(null , "Se ha negado el accseso a los usuarios de tipo profesor");   
                        }else if(nb_est_estu.equals("inactivo")&&id_rol==id_estu){
                            JOptionPane.showMessageDialog(null , "Se ha negado el accseso a los usuarios de tipo estudiante");   
                        }
//aqui......
                        if (id_rol == id_admin || id_rol == id_maestro) {
                           
                        if(clv.equals("12345")){ // md5 de 12345 :D
                             JOptionPane.showMessageDialog(null , "usted ha sido inscrito recientemente... a continuacion culminara su fase de registro");
                            
                             
                             String nombre_rol=m.Select2("tbl_rol_usr", "*", "id_rol_usr="+id_rol+"").getString("nb_rol_usr");
                           
                             m.setTipo(nombre_rol);
                             m.setClave(clv);
                              m.setNombre_usuario(usr);
                            admin_usuario ad = new admin_usuario (m);
                             ad.setVisible(true);
                              this.dispose();
                              
                        }else{
                            m.id_rol=id_rol;
                            m.setNombre_usuario(usr);
                            m.setClave(clv);
                            String nombre_rol=m.Select2("tbl_rol_usr", "*", "id_rol_usr="+id_rol+"").getString("nb_rol_usr");
                            m.setTipo(nombre_rol);
                            menu_principal mp = new menu_principal(m);
                            mp.setVisible(true);
                            this.dispose();
                            
                        } 
                        }
                            
                        else if("12345".equals(clv)) { // md5 encripcion de 12345 ._.
                                JOptionPane.showMessageDialog(null , "usted ha sido inscrito recientemente... a continuacion culminara su fase de registro");
                                String nombre_rol=m.Select2("tbl_rol_usr", "*", "id_rol_usr="+id_rol+"").getString("nb_rol_usr");
                                m.id_rol=id_rol;
                                m.setTipo(nombre_rol);
                                  m.setNombre_usuario(usr);
                            m.setClave(clv);
                                admin_usuario ad = new admin_usuario (m);
                                ad.setVisible(true);
                                this.dispose();
                                
                            } else{ menu_juego mj = new menu_juego(m);
                              m.setNombre_usuario(usr);
                            m.setClave(clv);
                            mj.setVisible(true);
                            this.dispose();
                            
                                            
                        
                        
                        }  
                        }
                        
                    } catch (SQLException ex) {                
                    Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
                }else {
                mensaje.setVisible(false);
                mensaje.setText("Usuario o Clave incorrecta");
                mensaje.setForeground(Color.RED);
                equivoco++;
                if(int_bloqueo==equivoco){
                    
                    //Gedeon1.inicio_bloqueado();
                    
                    //this.setVisible(false);
               }    
                }
                }
    }//GEN-LAST:event_boton_aceptarActionPerformed

    private void usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // recuperar contraseña ventana
        recuperarContrasena ven = new recuperarContrasena(this.m);
        ven.setLocationRelativeTo(null);
        ven.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por Jugar...Vuelve Pronto");
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveActionPerformed

    //
     public void main(ManejadorSQL m2) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        m=m2;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_principal(m).setVisible(true);
                
               
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_aceptar;
    private javax.swing.JPasswordField clave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel nombre_clave;
    private javax.swing.JLabel nombre_usuario;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private javax.swing.JButton salir;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
