/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gedeon1;

import base_dato.ManejadorSQL;
import base_dato.validaciones;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class MensajeEditor extends javax.swing.JFrame {

    /**
     * Creates new form MensajeEditor
     */
    public MensajeEditor() {
        initComponents();
        jTabbedPane1.setEnabledAt(1, false);
          ImageIcon img = new ImageIcon(getClass().getResource(Gedeon1.icono));
        this.setIconImage(img.getImage());
  
    }
    
    ArrayList <String> mensajes = new ArrayList<String>();
    ArrayList <Integer> ids = new ArrayList<Integer>();
    int msj_id = 0;
    
    public void actualizarListaGanar() {
        validaciones v = new validaciones();
        ManejadorSQL db = new ManejadorSQL("postgres", Gedeon1.ipcondb, "freddy", "1234", "org.postgresql.Driver", "5432", "jdbc:postgresql", "2", v);
        
        ResultSet rs = db.Select("tbl_msj_ganar", "id_msj, mensaje");
        mensajes.clear();
        ids.clear();
        try {
            while(rs.next()) {
                mensajes.add(rs.getString("mensaje"));
                ids.add(rs.getInt("id_msj"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(MensajeEditor.class.getName()).log(Level.SEVERE, null, ex);
            db.close();
        }
        jList1.setListData(mensajes.toArray());
        db.close();
    }
    
    public void actualizarListaPerder() {
        validaciones v = new validaciones();
        ManejadorSQL db = new ManejadorSQL("postgres", Gedeon1.ipcondb, "freddy", "1234", "org.postgresql.Driver", "5432", "jdbc:postgresql", "2", v);
        
        ResultSet rs = db.Select("tbl_msj_perder", "msj_id, mensaje");
        mensajes.clear();
        ids.clear();
        try {
            while(rs.next()) {
                mensajes.add(rs.getString("mensaje"));
                ids.add(rs.getInt("msj_id"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(MensajeEditor.class.getName()).log(Level.SEVERE, null, ex);
            db.close();
        }
        jList1.setListData(mensajes.toArray());
        db.close();
    }
    
    public void restablecerBotones() {
        botonEditar.setEnabled(false);
        botonBorrar.setEnabled(false);
    }
    
    public void establecerBotones() {
        botonEditar.setEnabled(true);
        botonBorrar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        seleccionListadoGanar = new javax.swing.JRadioButton();
        seleccionListadoPerder = new javax.swing.JRadioButton();
        botonBorrar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonNuevo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botonGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        seleccionMensajeGanar = new javax.swing.JRadioButton();
        seleccionMensajePerder = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        seleccionListadoGanar.setText("Mensajes Ganar");
        seleccionListadoGanar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionListadoGanarActionPerformed(evt);
            }
        });

        seleccionListadoPerder.setText("Mensajes Perder");
        seleccionListadoPerder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionListadoPerderActionPerformed(evt);
            }
        });

        botonBorrar.setText("Borrar Mensaje");
        botonBorrar.setEnabled(false);

        botonEditar.setText("Editar Mensaje");
        botonEditar.setEnabled(false);
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonNuevo.setText("Nuevo Mensaje");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(botonBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonNuevo)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seleccionListadoGanar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seleccionListadoPerder)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionListadoGanar)
                    .addComponent(seleccionListadoPerder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrar)
                    .addComponent(botonEditar)
                    .addComponent(botonNuevo)))
        );

        jTabbedPane1.addTab("Listado", jPanel1);

        botonGuardar.setText("Guardar");
        botonGuardar.setEnabled(false);
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        seleccionMensajeGanar.setText("Mensaje Ganar");
        seleccionMensajeGanar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionMensajeGanarActionPerformed(evt);
            }
        });

        seleccionMensajePerder.setText("Mensaje Perder");
        seleccionMensajePerder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionMensajePerderActionPerformed(evt);
            }
        });

        jLabel1.setText("Click en el Tab 'Listado' para cancelar.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(seleccionMensajeGanar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seleccionMensajePerder))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionMensajeGanar)
                    .addComponent(seleccionMensajePerder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(6, 6, 6))
        );

        jTabbedPane1.addTab("Editor", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        // nuevo mensaje
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void seleccionListadoGanarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionListadoGanarActionPerformed
        // handle del radio button
        seleccionListadoPerder.setSelected(false);
        this.restablecerBotones();
        // seleccionar tipo mensaje GANAR a mostrar listado
        this.actualizarListaGanar();
    }//GEN-LAST:event_seleccionListadoGanarActionPerformed

    private void seleccionListadoPerderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionListadoPerderActionPerformed
        
        // handle del radio button
        seleccionListadoGanar.setSelected(false);
        this.restablecerBotones();
        // seleccionar tipo mensaje PERDER a mostrar listado
        this.actualizarListaPerder();
    }//GEN-LAST:event_seleccionListadoPerderActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // click on this element
        if (!jList1.isSelectionEmpty()) {
            this.msj_id = jList1.getSelectedIndex();
            this.establecerBotones();
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // guardar mensaje
        if (jTextArea1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe escribir un mensaje...!");
            return;
        }
         String m=jTextArea1.getText();
        validaciones v = new validaciones();
        ManejadorSQL db = new ManejadorSQL("postgres", Gedeon1.ipcondb, "freddy", "1234", "org.postgresql.Driver", "5432", "jdbc:postgresql", "2", v);
        if(this.seleccionMensajeGanar.isSelected()){
        
       
        boolean existe=db.Select3("tbl_msj_ganar", "*", "mensaje='"+m+"'");
        if(existe==true){
            JOptionPane.showMessageDialog(null, "Este mensaje fue ingresado anteriormente... INGRESE UN NUEVO MENSAJE", "Acción no Ejecutada", JOptionPane.ERROR_MESSAGE);      
             jTextArea1.setText("");  
        }
        else{
              db.Insert("tbl_msj_ganar", "mensaje","'"+m+"'");
               seleccionMensajePerder.setSelected(false);
              seleccionMensajeGanar.setSelected(false);
              jTextArea1.setText("");  
              botonGuardar.setEnabled(false);
        }
        }
        if(this.seleccionMensajePerder.isSelected()){
    boolean existe=db.Select3("tbl_msj_perder", "*", "mensaje='"+m+"'");
    if(existe==true){
        JOptionPane.showMessageDialog(null, "Este mensaje fue ingresado anteriormente... INGRESE UN NUEVO MENSAJE", "Acción no Ejecutada", JOptionPane.ERROR_MESSAGE);      
             jTextArea1.setText("");  
    }else{
             db.Insert("tbl_msj_perder", "mensaje","'"+m+"'");
             seleccionMensajePerder.setSelected(false);
              seleccionMensajeGanar.setSelected(false);
              jTextArea1.setText("");  
              botonGuardar.setEnabled(false);
        
        }
        }
        
        
    
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        // TODO add your handling code her
    }//GEN-LAST:event_botonEditarActionPerformed

    private void seleccionMensajeGanarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionMensajeGanarActionPerformed
        // seleccionar a editar un mensaje de ganar
        botonGuardar.setEnabled(true);
        seleccionMensajePerder.setSelected(false);
    }//GEN-LAST:event_seleccionMensajeGanarActionPerformed

    private void seleccionMensajePerderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionMensajePerderActionPerformed
        // seleccionar a editar un mensaje de perder
        botonGuardar.setEnabled(true);
        seleccionMensajeGanar.setSelected(false);
    }//GEN-LAST:event_seleccionMensajePerderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MensajeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MensajeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MensajeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MensajeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MensajeEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton seleccionListadoGanar;
    private javax.swing.JRadioButton seleccionListadoPerder;
    private javax.swing.JRadioButton seleccionMensajeGanar;
    private javax.swing.JRadioButton seleccionMensajePerder;
    // End of variables declaration//GEN-END:variables
}
