/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gedeon1;

import base_dato.ManejadorSQL;
import javax.swing.ImageIcon;

/**
 *
 * @author Laptop
 */
public class menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form menu_principal
     */
    
    ManejadorSQL m;
    
    public menu_principal(ManejadorSQL m2) {
        initComponents();
        m=m2;
         ImageIcon img = new ImageIcon(getClass().getResource(Gedeon1.icono));
        this.setIconImage(img.getImage());
        this.setLocationRelativeTo(null);
        //System.out.println(m.getNombre_usuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boton_salir_mpp = new javax.swing.JButton();
        boton_inser_jugador = new javax.swing.JButton();
        boton_centropreg = new javax.swing.JButton();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        boton_detalleapp1 = new javax.swing.JButton();
        boton_centropreg1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Principal");

        boton_salir_mpp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_salir_mpp.setForeground(new java.awt.Color(0, 51, 204));
        boton_salir_mpp.setText("Salir");
        boton_salir_mpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salir_mppActionPerformed(evt);
            }
        });

        boton_inser_jugador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton_inser_jugador.setForeground(new java.awt.Color(0, 51, 204));
        boton_inser_jugador.setText("Administrar Usuarios");
        boton_inser_jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_inser_jugadorActionPerformed(evt);
            }
        });

        boton_centropreg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton_centropreg.setForeground(new java.awt.Color(0, 51, 204));
        boton_centropreg.setText("Centro de control de preguntas ");
        boton_centropreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_centropregActionPerformed(evt);
            }
        });

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen3.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        boton_detalleapp1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton_detalleapp1.setForeground(new java.awt.Color(0, 51, 204));
        boton_detalleapp1.setText("Mensajes (Ganar/Perder) Editor");
        boton_detalleapp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_detalleapp1ActionPerformed(evt);
            }
        });

        boton_centropreg1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton_centropreg1.setForeground(new java.awt.Color(0, 51, 204));
        boton_centropreg1.setText("Centro de configurcion de clave ");
        boton_centropreg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_centropreg1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(boton_salir_mpp)
                                .addComponent(boton_inser_jugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boton_centropreg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(boton_detalleapp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(boton_centropreg1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(239, 239, 239))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(boton_inser_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton_detalleapp1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton_centropreg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton_centropreg1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(boton_salir_mpp)))
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_salir_mppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salir_mppActionPerformed
//        inicio p1=new inicio ();
//        p1.setVisible(true);
        this.dispose();
        Gedeon1.iniciar_sistema();
    }//GEN-LAST:event_boton_salir_mppActionPerformed

    private void boton_inser_jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_inser_jugadorActionPerformed
        admin_usuario pr=new admin_usuario (m);
        pr.setVisible(true);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_boton_inser_jugadorActionPerformed

    private void boton_centropregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_centropregActionPerformed
        preguntas cp = new  preguntas(m);
        cp.setVisible(true);
        this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_boton_centropregActionPerformed

    private void boton_detalleapp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_detalleapp1ActionPerformed
   MensajeEditor me=new  MensajeEditor();
           me.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_detalleapp1ActionPerformed

    private void boton_centropreg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_centropreg1ActionPerformed
new claveConfiguracion (m).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_boton_centropreg1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(ManejadorSQL m2) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        m=m2;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_principal(m).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_centropreg;
    private javax.swing.JButton boton_centropreg1;
    private javax.swing.JButton boton_detalleapp1;
    private javax.swing.JButton boton_inser_jugador;
    private javax.swing.JButton boton_salir_mpp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
