/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gedeon1;

import base_dato.ManejadorSQL;
import base_dato.validaciones;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class recupera_clave extends javax.swing.JFrame {
    ManejadorSQL m;
 validaciones v = new validaciones();

    /**
     * Creates new form recupera_clave
     */
    public recupera_clave(ManejadorSQL m2) {
        m=m2;
        initComponents();
        labelnueva.setVisible(false);
        labelconf.setVisible(false);
        btnguardar.setVisible(false);
        llenar_preguntas();
         ImageIcon img = new ImageIcon(getClass().getResource(Gedeon1.icono));
        this.setIconImage(img.getImage());
   
        
    }
public void llenar_preguntas(){
    try {
            DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
            Class.forName("org.postgresql.Driver");
            Connection conexion = m.devolverconexion();//DriverManager.getConnection("jdbc:postgresql://localhost/dbsitxian", "importadoraxian", "sitvenpfi");
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM preguntas_secretas");
            combopreguntas.removeAllItems();
            modeloCombo.addElement("Seleccione una pregunta secreta");
            while (rs.next()) {
                modeloCombo.addElement(rs.getObject("nb_pregunta_secreta"));
            }
            rs.close();
            combopreguntas.setModel(modeloCombo);    
        } catch (SQLException ex) {
            Logger.getLogger(recupera_clave.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(recupera_clave.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelnombre = new javax.swing.JLabel();
        labelapellido = new javax.swing.JLabel();
        labelrespuesta = new javax.swing.JLabel();
        labelnueva = new javax.swing.JLabel();
        labelconf = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        texfielnombre = new javax.swing.JTextField();
        texfirespuesta = new javax.swing.JTextField();
        combopreguntas = new javax.swing.JComboBox();
        pasfielnueva = new javax.swing.JPasswordField();
        pasfieldcof = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RECUPERAR CONTRASEÑA");

        labelnombre.setText("Nombre de usuario:");

        labelapellido.setText("Pregunta secreta:");

        labelrespuesta.setText("Respuesta secreta:");

        labelnueva.setText("Nueva contraseña:");

        labelconf.setText("Confirmar contraseña:");

        jLabel6.setText("Recuperar  Contraseña");

        texfielnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfielnombreActionPerformed(evt);
            }
        });

        texfirespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfirespuestaActionPerformed(evt);
            }
        });

        combopreguntas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        pasfielnueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasfielnuevaActionPerformed(evt);
            }
        });

        pasfieldcof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasfieldcofActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnguardar))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelconf)
                                        .addComponent(labelnueva)
                                        .addComponent(labelrespuesta))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(texfielnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(texfirespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                            .addComponent(pasfielnueva)
                                            .addComponent(pasfieldcof, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(combopreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(labelnombre)
                            .addComponent(labelapellido)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnombre)
                    .addComponent(texfielnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelapellido)
                    .addComponent(combopreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelrespuesta)
                    .addComponent(texfirespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnueva)
                    .addComponent(pasfielnueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pasfieldcof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelconf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(jButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texfielnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfielnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfielnombreActionPerformed

    private void texfirespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfirespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfirespuestaActionPerformed

    private void pasfielnuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasfielnuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasfielnuevaActionPerformed

    private void pasfieldcofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasfieldcofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasfieldcofActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(texfielnombre.getText().equals("")||texfirespuesta.equals("")){
    
     JOptionPane.showMessageDialog(null, "todos los campos deben estar llenos ", "Acción no Ejecutada", JOptionPane.ERROR_MESSAGE);         
}else if(combopreguntas.getSelectedItem().toString().equals("Seleccione una pregunta secreta")){
JOptionPane.showMessageDialog(null, "Debe seleccionar una pregunta", "Acción no Ejecutada", JOptionPane.ERROR_MESSAGE);         
    
}else{
    try {
       
        String id_preg= m.Select2("preguntas_secretas", "*", "nb_pregunta_secreta='"+combopreguntas.getSelectedItem().toString()+"'").getString("id_preguntas_secreta");
        String id_usuario=m.Select2("usuarios", "*", "tx_login='" + texfielnombre.getText()).getString("id_usuario");
        String respuesta=m.Select2("tbl_preg_usr", "*", "id_usuario='" + id_usuario+"'").getString("tx_pregunta_secreta");
  if(texfirespuesta.getText().equals(respuesta)){
      labelnueva.setVisible(true);
        labelconf.setVisible(true);
        texfielnombre.setEditable(false);
        texfirespuesta.setEditable(false);
        combopreguntas.setEnabled(false);
        jButton1.setEnabled(false);
        btnguardar.setVisible(true);
        
  }
    }
    // TODO add your handling code here:
    catch (SQLException ex) {
        Logger.getLogger(recupera_clave.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
if(pasfielnueva.getText().equals("")||pasfieldcof.getText().equals("")){
JOptionPane.showMessageDialog(null, "todos los campos deben estar llenos ", "Acción no Ejecutada", JOptionPane.ERROR_MESSAGE);         
       
}else if (!pasfielnueva.getText().equals(pasfieldcof.getText())){
                JOptionPane.showMessageDialog(null, "Los campos contraseña y repetir contraseña deben ser iguales", "Acción no Ejecutada", JOptionPane.ERROR_MESSAGE);      
                pasfieldcof.setText("");
                pasfielnueva.setText("");
            }else{
 String id_usuario;
    try {
        id_usuario = m.Select2("usuarios", "*", "tx_login='" + texfielnombre.getName().toString()).getString("id_usuario");
    
 boolean list=m.Update("usuarios"," clave='"+pasfielnueva.getText()+"'", "id_usuario='"+id_usuario+"'");
    if(list==true){
        JOptionPane.showMessageDialog(null, "Contraseña_cambiada", "Acción Ejecutada", JOptionPane.INFORMATION_MESSAGE);
    new inicio ().setVisible(true);
    this.dispose();
    }
    
    else{
 JOptionPane.showMessageDialog(null, "Error", "Acción no Ejecutada", JOptionPane.ERROR_MESSAGE);
    }
    }catch (SQLException ex) {
        Logger.getLogger(recupera_clave.class.getName()).log(Level.SEVERE, null, ex);
    }
}
                // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      new inicio ().setVisible(true);
    this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(ManejadorSQL m2) {
        m=m2;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recupera_clave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recupera_clave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recupera_clave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recupera_clave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recupera_clave(m).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox combopreguntas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelapellido;
    private javax.swing.JLabel labelconf;
    private javax.swing.JLabel labelnombre;
    private javax.swing.JLabel labelnueva;
    private javax.swing.JLabel labelrespuesta;
    private javax.swing.JPasswordField pasfieldcof;
    private javax.swing.JPasswordField pasfielnueva;
    private javax.swing.JTextField texfielnombre;
    private javax.swing.JTextField texfirespuesta;
    // End of variables declaration//GEN-END:variables
}
