/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gedeon1;

import base_dato.ManejadorSQL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class recuperarContrasena extends javax.swing.JFrame {
    /**
     * Creates new form recuperarContrasena
     */
    public recuperarContrasena(ManejadorSQL db) {
        initComponents();
        this.db = db;
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3, false);
        jTabbedPane1.setEnabledAt(4, false);
    }
    
    public void restablecerFormulario() {
        jTextField1.setText("");
        jTextField3.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        jPasswordField3.setText("");
        jPasswordField4.setText("");
        jPasswordField5.setText("");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private ManejadorSQL db = null;
    private int usuario_id = -1;
    private String respuesta_secreta = "";
    private String clave_vieja = "";
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jPasswordField5 = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPasswordField3 = new javax.swing.JPasswordField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("Ingrese su nombre de usuario o cedula");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cedula", "Nombre" }));

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton1)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Paso 1", jPanel1);

        jLabel2.setText("¡Muy bien! Le hemos encontrado, ¿que desea hacer exactamente?");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cambiar Contraseña", "Recuperar Contraseña" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton2.setText("Decidir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Paso 2", jPanel2);

        jLabel6.setText("Responda su pregunta secreta");

        jLabel7.setText("<aqui va la pregunta>");

        jButton5.setText("Responder");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setText("Respuesta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Recuperar", jPanel3);

        jLabel3.setText("Contraseña Vieja");

        jLabel4.setText("Contraseña Nueva");

        jLabel5.setText("Repetir Contraseña Nueva");

        jButton3.setText("Cambiar Contraseña");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField5, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addGap(61, 61, 61))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cambiar", jPanel4);

        jLabel9.setText("Ingrese su nueva contraseña!");

        jLabel10.setText("Nueva Contraseña");

        jLabel11.setText("Repetir Contraseña Nueva");

        jButton6.setText("Registrar Nueva Contraseña");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordField3, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(jPasswordField4)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jButton6)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nueva Contraseña", jPanel5);

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // encontrar nombre de usuario o contraseña
   
        switch(jComboBox1.getSelectedItem().toString()) {
            case "Cedula":
                try {
                   
                   this.usuario_id = this.db.Select2("usuarios", "id_usuario", "cedula = '"+jTextField1.getText()+"'").getInt("id_usuario");
                    
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "La cedula introducida no existe, vuelva a intentarlo. (0x0)");
                    Logger.getLogger(recuperarContrasena.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NullPointerException ex) {
                    JOptionPane.showMessageDialog(null, "La cedula introducida no existe, vuelva a intentarlo.(0x1)");
                    Logger.getLogger(recuperarContrasena.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(this.usuario_id > 0) {
                    jTabbedPane1.setSelectedIndex(1);
                }
                break;
            case "Nombre":
                try {
                       this.usuario_id = this.db.Select2("usuarios", "id_usuario", "nombre = '"+jTextField1.getText()+"'").getInt("id_usuario");
                       if (this.usuario_id > 0) {
                            jTabbedPane1.setEnabledAt(1, true);
                       }

                } catch (SQLException ex) {
                    Logger.getLogger(recuperarContrasena.class.getName()).log(Level.SEVERE, null, ex);
                }
                    
                
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // decision del usuario
        switch(jComboBox2.getSelectedItem().toString()) {
            case "Cambiar Contraseña":
        try {
            this.clave_vieja = db.Select2("usuarios","clave", "id_usuario="+usuario_id).getString("clave");
        } catch (SQLException ex) {
            Logger.getLogger(recuperarContrasena.class.getName()).log(Level.SEVERE, null, ex);
        }
                jTabbedPane1.setSelectedIndex(3);
                
                break;
            case "Recuperar Contraseña":
                Connection con;
                con = this.db.getConexion();
                
                
            try {
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT ps.nb_pregunta_secreta as pregunta, pg.tx_respuesta as respuesta FROM tbl_preg_usr pg"
                            + " INNER JOIN preguntas_secretas ps ON ps.id_preguntas_secreta = pg.id_pregunta_secreta"
                            + " WHERE pg.id_usuario = "+this.usuario_id);
                if (rs.next()) {
                    jLabel7.setText(rs.getString("pregunta"));
                    this.respuesta_secreta = rs.getString("respuesta");
                    jTabbedPane1.setSelectedIndex(2);
                }
                stmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(recuperarContrasena.class.getName()).log(Level.SEVERE, null, ex);
            }
            
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // responder pregunta
        if(this.jTextField3.getText().equals(this.respuesta_secreta)) {
            jTabbedPane1.setSelectedIndex(4);
        } else {
            JOptionPane.showMessageDialog(null, "Respuesta incorrecta!");
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // nueva contraseña recuperada
        int mayusculas, minusculas, maximo, minimo;
        ResultSet rs = db.Select("tbl_conf_clave", "long_min, long_max, cant_mayus, cant_minus", "activo = '1'");
        maximo = 8;
        minimo = 4;
        mayusculas = 0;
        minusculas = 0;
        
        try {
            if (rs.next()) {
                mayusculas = rs.getInt("cant_mayus");
                minusculas = rs.getInt("cant_minus");
                maximo = rs.getInt("long_max");
                minimo = rs.getInt("long_min");
            }
        } catch (SQLException ex) {
            Logger.getLogger(admin_usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (jPasswordField3.toString().equals("")||jPasswordField4.toString().equals("")){
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos", "Acción no Ejecutada", JOptionPane.ERROR_MESSAGE);      
               
                }else if(!jPasswordField3.getText().equals(jPasswordField4.getText())){
            JOptionPane.showMessageDialog(null, "Los Campos nueva contraseña y  confirmar contraseña deben ser iguales", "Acción no Ejecutada", JOptionPane.ERROR_MESSAGE);      
                  
                }   else if (jPasswordField3.getText().toString().length()>maximo || jPasswordField3.getText().toString().length()<minimo) {
                JOptionPane.showMessageDialog(null,"la clave debe poseer entre "+minimo+" y "+maximo+" caracteres");
                
            } else if (db.val.contar_mayusculas(jPasswordField3.getText()) < mayusculas) {
                JOptionPane.showMessageDialog(null,"La contraseña debe tener al menos"+mayusculas+"letars en mayusculas");
            }else if(db.val.contar_minusculas(jPasswordField3.getText()) < minusculas){
                JOptionPane.showMessageDialog(null,"La contraseña debe tener al menos"+minusculas+"letars en minusculas" );
            }else{
            if (this.db.Update("usuarios", "clave = '"+this.db.getStringMessageDigest(jPasswordField3.getText(), "md5")+"'", "id_usuario = "+this.usuario_id)) {
                JOptionPane.showMessageDialog(null, "Clave cambiada efectivamente");
                jTabbedPane1.setSelectedIndex(0);
                this.restablecerFormulario();
            }
        }
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // cerrar ventana
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // cambiar contrasteeña
        int mayusculas, minusculas, maximo, minimo;
        ResultSet rs = db.Select("tbl_conf_clave", "long_min, long_max, cant_mayus, cant_minus", "activo = '1'");
        maximo = 8;
        minimo = 4;
        mayusculas = 0;
        minusculas = 0;
        
        try {
            if (rs.next()) {
                mayusculas = rs.getInt("cant_mayus");
                minusculas = rs.getInt("cant_minus");
                maximo = rs.getInt("long_max");
                minimo = rs.getInt("long_min");
            }   
        } catch (SQLException ex) {
            Logger.getLogger(admin_usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    if(jPasswordField5.getText().equals("")||jPasswordField2.getText().equals("")||jPasswordField1.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos", "Acción no Ejecutada", JOptionPane.ERROR_MESSAGE);      
               
    }
     else if (this.db.getStringMessageDigest(jPasswordField5.getText(), "md5").equals(this.clave_vieja.trim())){
        if(!jPasswordField2.getText().equals(jPasswordField1.getText())){
        JOptionPane.showMessageDialog(null, "Los campos contraseña nueva y confirmar contraseña deben ser iguales");
                       
            
        } else if (jPasswordField1.getText().toString().length()>maximo || jPasswordField1.getText().toString().length()<minimo) {
                JOptionPane.showMessageDialog(null,"la clave debe poseer entre  "+minimo+" y "+maximo+ "caracteres");
                
            } else if (db.val.contar_mayusculas(jPasswordField1.getText())<mayusculas) {
                
                JOptionPane.showMessageDialog(null,"La contraseña debe tener al menos  "+mayusculas+"  letars en mayusculas");
            }else if(db.val.contar_minusculas(jPasswordField1.getText())<minusculas){
                JOptionPane.showMessageDialog(null,"La contraseña debe tener al menos  "+minusculas+"  letars en minusculas" );
            }
         else{
                boolean si=db.Update("usuarios", "clave='"+db.getStringMessageDigest(jPasswordField1.getText(), "md5")+"'", "id_usuario="+usuario_id+"");
                   if(si==true){
                   JOptionPane.showMessageDialog(null, "Su contraseña ha sido cambiada exitosamente");
                   }
            }
                
        }else
        JOptionPane.showMessageDialog(null, "Contraseña antigua no encontrada", "Acción no Ejecutada", JOptionPane.ERROR_MESSAGE);      
                jPasswordField1.setText("");
                jPasswordField2.setText("");
                jPasswordField5.setText("");
    
    }//GEN-LAST:event_jButton3ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
